### PR TITLE
Update load_db #25

### LINKED ISSUE #25: Wrong default behaviour of `load_db` if multiple tables with same `table_name_pattern` exist in CDM instance
When using the function `load_db` using dummy CDM data with more than one csv with e.g. MEDICINES data (in my case: `MEDICINES_3.csv` and `MEDICINES_PAXLOVID.csv`), the csv that is loaded secondly needs to contain the same columns as the first csv. In my use case, this wasn't true, and as a consequence the message was printed to the console, subsequently resulting in an error:

```
[1] "[load_db]: Loading: MEDICINES_3.csv 1/2"
[1] "[load_db]: Loading: MEDICINES_PAXLOVID.csv 2/2"
[1] "[load_db]: The following columns are missing in the input: y"
Error: near "ADD": syntax error
```
The message is a consequence of a check done [here](https://github.com/UMC-Utrecht-RWE/T2-DataManagementModel/blob/daae65ad025791af414d5f01e888b32944a1e05a/R/load_db.R#L68-L79). Subsequently, `load_db` [tries to alter the table by adding in the missing columns](https://github.com/UMC-Utrecht-RWE/T2-DataManagementModel/blob/daae65ad025791af414d5f01e888b32944a1e05a/R/load_db.R#L81-L83), resulting in the error as shown above.

I think the desired behaviour here is to:
- Change the message to something more informative like: "The following columns do not exist in <<MEDICINES_PAXLOVID.csv>> but do exist in (one of the) other tables containing MEDICINES data: <<insert columns>>. The following columns do exist in <<MEDICINES_PAXLOVID.csv>> and did not exist in (one of the) other tables containing MEDICINES data yet: <<insert columns>>. Columns <<xxxx>> and <<yyyy>> are added to table MEDICINES.
And subsequently add all the columns to the MEDICINES table in the db:
- The columns in `MEDICINES_3.csv` and NOT in `MEDICINES_PAXLOVID.csv` AND 
- The columns in `MEDICINES_PAXLOVID.csv` and NOT in `MEDICINES_3.csv`
In this way the two tables can be appended and the non-overlapping columns `NA`.

### PR DESCRIPTION
**Pull request by acidroyo**
Closes #25

### CODE REVIEW

**Review by LindaNab — CHANGES_REQUESTED** [review]
Hi @acidroyo as a first step, just tried to use the adapted function to load the edited CPRD database. It still throws an error:
```
[1] "[load_db]: The following columns are missing in the NEW INPUT: y"
[1] "[load_db]: Addding column: y to table MEDICINES to NEW INPUT"
Error in eval(lhs, parent.frame(), parent.frame()) : object 'x' not found
```
Please can you fix before I continue reviewing the proposed changes? 
Thx!

**Comment by acidroyo** [comment]
@LindaNab where are you trying the package in the Paxlovid study? This is not yet updated with the version of this PR.

**Comment by LindaNab** [comment]
Morning @acidroyo can you elaborate why the proposed changes do not yet solve the issue we encountered when loading the edited CPRD data? I was hoping it would.

Just to make myself more clear, I'm trying to load the edited CPRD data by installing and loading the package locally (using the version of the code of this PR) and the following script:

```
library(data.table)
library(DBI)

dir_d2_db <- file.path("..", "Paxlovid-1047", "data", "D2_cdm", "d2_test.db")
db_connection_origin <- dbConnect(RSQLite::SQLite(), dir_d2_db)
dir_data <- file.path("..", "Paxlovid-1047", "data","D2_cdm","CPRD_EDITED_PAXLOVID")
filepath_cdm_metadata <-
  file.path("..", "Paxlovid-1047", "transformations", "common_configuration", "CDM_metadata.rds")
cdm_metadata <- as.data.table(readRDS(filepath_cdm_metadata))
cdm_tables_names <- c(
  "PERSONS", "VACCINES", "OBSERVATION_PERIODS", "MEDICAL_OBSERVATIONS",
  "MEDICINES", "EVENTS", "SURVEY_OBSERVATIONS", "SURVEY_ID", "VISIT_OCCURRENCE"
)

load_db(
  db_connection = db_connection_origin, csv_path_dir = dir_data,
  cdm_metadata = cdm_metadata, cdm_tables_names = cdm_tables_names
)

dbDisconnect(db_connection_origin)
```

**Review by LindaNab — APPROVED** [review]
Hi @acidroyo it all works good. Just pushed a commit with some suggestions to clarify language - feel free to adapt further!

**Pull request merged**
